-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 13:13:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FirstProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FirstProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FirstProject` DEFAULT CHARACTER SET utf8 ;
USE `FirstProject` ;

-- -----------------------------------------------------
-- Table `FirstProject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FirstProject`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(100) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
